// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/storage/storage.go

// Package mock_storage is a generated GoMock package.
package mock_storage

import (
	reflect "reflect"

	models "github.com/chemax/url-shorter/models"
	gomock "github.com/golang/mock/gomock"
)

// Mockconfiger is a mock of configer interface.
type Mockconfiger struct {
	ctrl     *gomock.Controller
	recorder *MockconfigerMockRecorder
}

// MockconfigerMockRecorder is the mock recorder for Mockconfiger.
type MockconfigerMockRecorder struct {
	mock *Mockconfiger
}

// NewMockconfiger creates a new mock instance.
func NewMockconfiger(ctrl *gomock.Controller) *Mockconfiger {
	mock := &Mockconfiger{ctrl: ctrl}
	mock.recorder = &MockconfigerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockconfiger) EXPECT() *MockconfigerMockRecorder {
	return m.recorder
}

// GetDBUse mocks base method.
func (m *Mockconfiger) GetDBUse() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDBUse")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetDBUse indicates an expected call of GetDBUse.
func (mr *MockconfigerMockRecorder) GetDBUse() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDBUse", reflect.TypeOf((*Mockconfiger)(nil).GetDBUse))
}

// GetSavePath mocks base method.
func (m *Mockconfiger) GetSavePath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSavePath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSavePath indicates an expected call of GetSavePath.
func (mr *MockconfigerMockRecorder) GetSavePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSavePath", reflect.TypeOf((*Mockconfiger)(nil).GetSavePath))
}

// Mockloggerer is a mock of loggerer interface.
type Mockloggerer struct {
	ctrl     *gomock.Controller
	recorder *MockloggererMockRecorder
}

// MockloggererMockRecorder is the mock recorder for Mockloggerer.
type MockloggererMockRecorder struct {
	mock *Mockloggerer
}

// NewMockloggerer creates a new mock instance.
func NewMockloggerer(ctrl *gomock.Controller) *Mockloggerer {
	mock := &Mockloggerer{ctrl: ctrl}
	mock.recorder = &MockloggererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockloggerer) EXPECT() *MockloggererMockRecorder {
	return m.recorder
}

// Debugln mocks base method.
func (m *Mockloggerer) Debugln(args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debugln", varargs...)
}

// Debugln indicates an expected call of Debugln.
func (mr *MockloggererMockRecorder) Debugln(args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugln", reflect.TypeOf((*Mockloggerer)(nil).Debugln), args...)
}

// Error mocks base method.
func (m *Mockloggerer) Error(args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockloggererMockRecorder) Error(args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*Mockloggerer)(nil).Error), args...)
}

// MockdataBaser is a mock of dataBaser interface.
type MockdataBaser struct {
	ctrl     *gomock.Controller
	recorder *MockdataBaserMockRecorder
}

// MockdataBaserMockRecorder is the mock recorder for MockdataBaser.
type MockdataBaserMockRecorder struct {
	mock *MockdataBaser
}

// NewMockdataBaser creates a new mock instance.
func NewMockdataBaser(ctrl *gomock.Controller) *MockdataBaser {
	mock := &MockdataBaser{ctrl: ctrl}
	mock.recorder = &MockdataBaserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdataBaser) EXPECT() *MockdataBaserMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method.
func (m *MockdataBaser) BatchDelete(arg0 []string, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BatchDelete", arg0, arg1)
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockdataBaserMockRecorder) BatchDelete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockdataBaser)(nil).BatchDelete), arg0, arg1)
}

// Get mocks base method.
func (m *MockdataBaser) Get(code string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", code)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockdataBaserMockRecorder) Get(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockdataBaser)(nil).Get), code)
}

// GetAllURLs mocks base method.
func (m *MockdataBaser) GetAllURLs(userID string) ([]models.URLWithShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllURLs", userID)
	ret0, _ := ret[0].([]models.URLWithShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllURLs indicates an expected call of GetAllURLs.
func (mr *MockdataBaserMockRecorder) GetAllURLs(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllURLs", reflect.TypeOf((*MockdataBaser)(nil).GetAllURLs), userID)
}

// Ping mocks base method.
func (m *MockdataBaser) Ping() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockdataBaserMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockdataBaser)(nil).Ping))
}

// SaveURL mocks base method.
func (m *MockdataBaser) SaveURL(code, URL, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveURL", code, URL, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveURL indicates an expected call of SaveURL.
func (mr *MockdataBaserMockRecorder) SaveURL(code, URL, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveURL", reflect.TypeOf((*MockdataBaser)(nil).SaveURL), code, URL, userID)
}

// Use mocks base method.
func (m *MockdataBaser) Use() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Use")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Use indicates an expected call of Use.
func (mr *MockdataBaserMockRecorder) Use() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Use", reflect.TypeOf((*MockdataBaser)(nil).Use))
}
